
- hosts: cicd
  tasks:

  - name: Ensure Java is installed
    become: yes
    apt: pkg=openjdk-8-jdk state=present

  - name: Select correct java version selected 
    alternatives: 
      name: java 
      path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  - name: Add Jenkins apt repository key.
    become: yes
    apt_key:
      url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
      state: present

  - name: Add Jenkins apt repository
    become: yes
    apt_repository:
      repo: "deb http://pkg.jenkins-ci.org/debian binary/"
      state: present
      update_cache: yes

  - name: Ensure Jenkins is installed
    become: yes
    apt: pkg=jenkins state=present

  - name: Install pip
    become: yes
    apt: pkg=python-pip state=present


  - name: Ensure ansible is installed
    become: yes
    pip:
      name: ansible
      executable: pip
